// Translations
const TRANSLATIONS = {
    en: {
        nav_home: "Home",
        nav_how: "How it Works",
        nav_insp: "Inspiration",
        nav_saved: "❤️ Saved Ideas",
        hero_title: "Don't Toss It, Transform It",
        hero_desc: "Discover creative, sustainable ways to repurpose everyday items with the power of AI.",
        upload_title: "Upload your item",
        upload_desc: "Drag & drop an image here, or click to select",
        upload_btn: "Choose File",
        analyze_btn: "✨ Generate Ideas",
        results_title: "Upcycling Ideas for:",
        saved_title: "Your Saved Collection ❤️",
        saved_empty: "You haven't saved any ideas yet. Start analyzing items to build your collection!",
        saved_btn_find: "Find Ideas",
        how_title: "How It Works",
        how_desc: "Upcycle AI uses advanced image recognition to identify discarded items and suggests creative DIY projects. Our goal is to promote sustainability by extending the lifecycle of everyday objects.",
        step1_title: "1. Identify",
        step1_desc: "Upload a photo of any item you're about to throw away—bottles, boxes, old clothes, or furniture.",
        step2_title: "2. Brainstorm",
        step2_desc: "Our AI analyzes the material and shape to generate unique, practical, and aesthetic upcycling ideas.",
        step3_title: "3. Create",
        step3_desc: "Follow the simple guides, complete with tool lists and difficulty ratings, to build something new.",
        gallery_title: "Inspiration Gallery",
        gallery_desc: "See what's possible. Here are some popular projects generated by our community.",
        gal1_title: "Wine Bottle Lamp",
        gal1_desc: "Turn empty glass bottles into elegant table lamps using simple fairy lights or a lamp kit.",
        gal2_title: "Denim Tote Bag",
        gal2_desc: "Repurpose old jeans into a sturdy, stylish tote bag perfect for grocery shopping.",
        gal3_title: "Tin Can Planters",
        gal3_desc: "Clean tin cans, paint them with vibrant colors, and use them to grow kitchen herbs.",
        gal4_title: "Ladder Bookshelf",
        gal4_desc: "Mount an old wooden ladder horizontally on the wall for a rustic, space-saving bookshelf.",
        loading_text: "Scanning your item for potential...",
        footer_text: "&copy; 2026 Upcycle AI. Promoting sustainable living one project at a time.",
        tools_label: "You'll need:",
        save_btn: "Save",
        saved_btn: "Saved",
        share_btn: "Share",
        share_msg: "Check out this upcycling idea: ",
        share_success: "Link copied to clipboard!",
        // New How It Works & Tips
        how_step1_detail: "Look around for items you don't use anymore—empty jars, cardboard boxes, old t-shirts, or even broken furniture.",
        how_step2_detail: "Our AI technology identifies the object's material, shape, and condition to suggest the best repurposing projects.",
        how_step3_detail: "We provide a step-by-step guide, including a list of necessary tools and the estimated difficulty level, so you can start creating immediately.",
        tip_title: "Pro Tips for Best Results",
        tip_1_title: "Good Lighting",
        tip_1_desc: "Take photos in a well-lit area so the AI can clearly see the texture and details.",
        tip_2_title: "Clear Background",
        tip_2_desc: "Place the item against a plain background to help the AI isolate the object.",
        tip_3_title: "One Item at a Time",
        tip_3_desc: "For the most accurate ideas, scan one main item per photo.",
        faq_title: "Frequently Asked Questions",
        faq_q1: "Is this service free?",
        faq_a1: "Yes! Upcycle AI is completely free to use for generating upcycling ideas.",
        faq_q2: "Do I need to sign up?",
        faq_a2: "No, you can start generating ideas instantly without an account. We use browser storage to save your favorite ideas.",
        faq_q3: "What kind of items work best?",
        faq_a3: "Common household waste like glass bottles, tin cans, cardboard, denim, and plastic containers works best.",
        cta_title: "Ready to Start?",
        cta_btn: "Upload Item Now",
        // Inspiration Page
        insp_hero_title: "Community Creations",
        insp_hero_desc: "Explore a curated collection of upcycling projects from our global community.",
        filter_all: "All",
        filter_lighting: "Lighting",
        filter_fashion: "Fashion",
        filter_garden: "Garden",
        filter_decor: "Home Decor",
        featured_tag: "Featured Project",
        featured_title: "Vertical PET Bottle Garden",
        featured_desc: "A sustainable solution for urban gardening using recycled plastic bottles. Perfect for balconies and small kitchens.",
        cta_submit_title: "Made Something Cool?",
        cta_submit_desc: "Share your upcycling project with the community and inspire others!",
        cta_submit_btn: "Submit Project",
        // Static Content (Index)
        why_upcycle_title: "Why Upcycle?",
        why_upcycle_desc: "Upcycling is more than just a trend; it's a necessary shift towards a sustainable future. By repurposing items, we reduce landfill waste, conserve resources, and unleash our creativity. Every bottle, box, or piece of fabric has the potential to become something beautiful and functional.",
        feature_1_title: "Eco-Friendly",
        feature_1_desc: "Reduce your carbon footprint by giving old items a second life instead of buying new.",
        feature_2_title: "Cost-Effective",
        feature_2_desc: "Save money on home decor and organizers by using materials you already have.",
        feature_3_title: "Creative Outlet",
        feature_3_desc: "Express your unique style and improved your DIY skills with personalized projects.",
        popular_ideas_title: "Popular Upcycling Ideas",
        // Popular Cards
        pop_type_decor: "Decor",
        pop_type_storage: "Storage",
        pop_type_fashion: "Fashion",
        pop_diff_easy: "Easy",
        pop_diff_medium: "Medium",
        pop_card1_title: "Glass Jar Terrarium",
        pop_card1_desc: "Create a miniature ecosystem in an old pasta sauce jar. Perfect for succulents and moss.",
        pop_card1_tool1: "Clean Jar",
        pop_card1_tool2: "Soil",
        pop_card1_tool3: "Pebbles",
        pop_card2_title: "Cereal Box Organizer",
        pop_card2_desc: "Cut cereal boxes at an angle to create stylish magazine holders or paper organizers.",
        pop_card2_tool1: "Scissors",
        pop_card2_tool2: "Wrapping Paper",
        pop_card2_tool3: "Glue",
        pop_card3_title: "T-Shirt Yarn Rug",
        pop_card3_desc: "Turn old t-shirts into yarn and crochet or braid a colorful, durable rug for your home.",
        pop_card3_tool1: "Old Tees",
        pop_card3_tool2: "Scissors",
        pop_card3_tool3: "Crochet Hook (Opt)"
    },
    ko: {
        nav_home: "홈",
        nav_how: "사용 방법",
        nav_insp: "영감 얻기",
        nav_saved: "❤️ 내 보관함",
        hero_title: "버리지 말고, 변신시키세요",
        hero_desc: "AI의 힘으로 일상 속 물건들을 창의적이고 지속 가능한 방식으로 재사용하는 방법을 발견하세요.",
        upload_title: "물건 사진 업로드",
        upload_desc: "이미지를 드래그하거나 클릭하여 선택하세요",
        upload_btn: "파일 선택",
        analyze_btn: "✨ 아이디어 생성하기",
        results_title: "업사이클링 아이디어:",
        saved_title: "나의 보관함 ❤️",
        saved_empty: "아직 저장된 아이디어가 없습니다. 물건을 분석하고 아이디어를 모아보세요!",
        saved_btn_find: "아이디어 찾기",
        how_title: "사용 방법",
        how_desc: "Upcycle AI는 고급 이미지 인식을 사용하여 버려진 물건을 식별하고 창의적인 DIY 프로젝트를 제안합니다. 우리의 목표는 일상 물건의 수명을 연장하여 지속 가능성을 촉진하는 것입니다.",
        step1_title: "1. 식별 (Identify)",
        step1_desc: "버리려는 물건(병, 상자, 헌 옷, 가구 등)의 사진을 업로드하세요.",
        step2_title: "2. 브레인스토밍 (Brainstorm)",
        step2_desc: "AI가 재질과 모양을 분석하여 독특하고 실용적이며 심미적인 업사이클링 아이디어를 생성합니다.",
        step3_title: "3. 제작 (Create)",
        step3_desc: "도구 목록과 난이도가 포함된 간단한 가이드를 따라 새로운 물건을 만들어보세요.",
        gallery_title: "영감 갤러리",
        gallery_desc: "가능성을 확인해보세요. 커뮤니티에서 생성된 인기 프로젝트들입니다.",
        gal1_title: "와인병 램프",
        gal1_desc: "빈 유리병에 페어리 라이트나 램프 키트를 넣어 우아한 테이블 램프로 변신시키세요.",
        gal2_title: "청바지 토트백",
        gal2_desc: "헌 청바지를 튼튼하고 스타일리시한 장바구니용 토트백으로 리폼해보세요.",
        gal3_title: "통조림 캔 화분",
        gal3_desc: "통조림 캔을 씻어 밝은 색으로 칠하고 주방용 허브를 키우는 화분으로 사용하세요.",
        gal4_title: "사다리 책장",
        gal4_desc: "오래된 나무 사다리를 벽에 수평으로 설치하여 소박하고 공간 절약형인 책장을 만드세요.",
        loading_text: "잠재력을 분석하는 중...",
        footer_text: "&copy; 2026 Upcycle AI. 지속 가능한 생활을 위한 작은 실천.",
        tools_label: "준비물:",
        save_btn: "저장",
        saved_btn: "저장됨",
        share_btn: "공유",
        share_msg: "이 업사이클링 아이디어 확인해보세요: ",
        share_success: "링크가 복사되었습니다!",
        // New How It Works & Tips
        how_step1_detail: "더 이상 사용하지 않는 물건—빈 병, 택배 박스, 낡은 티셔츠, 혹은 부서진 가구 등을 찾아보세요.",
        how_step2_detail: "우리의 AI 기술이 물건의 재질, 모양, 상태를 분석하여 최적의 리폼 프로젝트를 제안합니다.",
        how_step3_detail: "필요한 도구 목록과 예상 난이도가 포함된 단계별 가이드를 제공하여 즉시 제작을 시작할 수 있습니다.",
        tip_title: "더 좋은 결과를 위한 팁",
        tip_1_title: "좋은 조명",
        tip_1_desc: "AI가 질감과 디테일을 명확하게 볼 수 있도록 밝은 곳에서 촬영하세요.",
        tip_2_title: "깔끔한 배경",
        tip_2_desc: "AI가 물체만 정확히 인식할 수 있도록 단순한 배경에 물건을 놓아주세요.",
        tip_3_title: "한 번에 하나씩",
        tip_3_desc: "가장 정확한 아이디어를 얻으려면 한 번에 하나의 물건만 스캔하는 것이 좋습니다.",
        faq_title: "자주 묻는 질문 (FAQ)",
        faq_q1: "이 서비스는 무료인가요?",
        faq_a1: "네! Upcycle AI는 업사이클링 아이디어를 생성하는 데 완전히 무료입니다.",
        faq_q2: "회원가입이 필요한가요?",
        faq_a2: "아니요, 계정 없이 즉시 아이디어를 생성할 수 있습니다. 즐겨찾기 저장은 브라우저 저장소를 사용합니다.",
        faq_q3: "어떤 물건이 가장 잘 되나요?",
        faq_a3: "유리병, 통조림 캔, 골판지 박스, 청바지, 플라스틱 용기 같은 일반적인 가정 폐기물이 가장 적합합니다.",
        cta_title: "시작할 준비가 되셨나요?",
        cta_btn: "지금 물건 업로드하기",
        // Inspiration Page
        insp_hero_title: "커뮤니티 작품",
        insp_hero_desc: "전 세계 커뮤니티에서 공유된 창의적인 업사이클링 프로젝트를 만나보세요.",
        filter_all: "전체",
        filter_lighting: "조명",
        filter_fashion: "패션",
        filter_garden: "정원/식물",
        filter_decor: "홈 데코",
        featured_tag: "이달의 추천",
        featured_title: "페트병 수직 정원",
        featured_desc: "재활용 페트병을 활용한 지속 가능한 도시 정원입니다. 베란다나 작은 주방에 완벽합니다.",
        cta_submit_title: "멋진 작품을 만드셨나요?",
        cta_submit_desc: "당신의 업사이클링 프로젝트를 커뮤니티에 공유하고 다른 사람들에게 영감을 주세요!",
        cta_submit_btn: "프로젝트 제출하기",
        // Static Content (Index)
        why_upcycle_title: "왜 업사이클링인가요?",
        why_upcycle_desc: "업사이클링은 단순한 유행이 아니라 지속 가능한 미래를 위한 필수적인 변화입니다. 물건을 재사용함으로써 우리는 매립 쓰레기를 줄이고 자원을 절약하며 창의력을 발휘할 수 있습니다. 모든 병, 상자, 천 조각은 아름답고 실용적인 무언가가 될 잠재력을 가지고 있습니다.",
        feature_1_title: "친환경적",
        feature_1_desc: "새 물건을 사는 대신 낡은 물건에 새 생명을 불어넣어 탄소 발자국을 줄이세요.",
        feature_2_title: "경제적",
        feature_2_desc: "이미 가지고 있는 재료를 사용하여 홈 데코와 정리 용품 비용을 절약하세요.",
        feature_3_title: "창의적 활동",
        feature_3_desc: "나만의 맞춤형 프로젝트로 독특한 스타일을 표현하고 DIY 기술을 향상시키세요.",
        popular_ideas_title: "인기있는 업사이클링 아이디어",
        // Popular Cards
        pop_type_decor: "데코",
        pop_type_storage: "수납",
        pop_type_fashion: "패션",
        pop_diff_easy: "쉬움",
        pop_diff_medium: "보통",
        pop_card1_title: "유리병 테라리움",
        pop_card1_desc: "다 쓴 파스타 소스 병에 작은 생태계를 만들어보세요. 다육식물과 이끼에 적합합니다.",
        pop_card1_tool1: "깨끗한 병",
        pop_card1_tool2: "흙",
        pop_card1_tool3: "자갈",
        pop_card2_title: "시리얼 박스 정리함",
        pop_card2_desc: "시리얼 박스를 비스듬히 잘라 스타일리시한 잡지 꽂이나 서류 정리함을 만드세요.",
        pop_card2_tool1: "가위",
        pop_card2_tool2: "포장지",
        pop_card2_tool3: "풀",
        pop_card3_title: "티셔츠 실 러그",
        pop_card3_desc: "낡은 티셔츠를 실로 만들어 집안을 화사하게 해줄 튼튼하고 다채로운 러그를 짜보세요.",
        pop_card3_tool1: "헌 티셔츠",
        pop_card3_tool2: "가위",
        pop_card3_tool3: "코바늘 (선택)"
    }
};

// Mock Data
const MOCK_DATA = {
    en: {
        "detected_item": "Empty Glass Wine Bottle",
        "ideas": [
            {
                "id": 1,
                "type": "Easy Start",
                "title": "Minimalist Single-Stem Vase",
                "description": "Transform that bottle into a chic vase by removing the label and wrapping the neck with twine for a rustic touch.",
                "difficulty": "Easy",
                "required_tools": ["Warm Water", "Scrubbing Sponge", "Jute Twine", "Scissors", "Clear Glue"]
            },
            {
                "id": 2,
                "type": "Aesthetic Decor",
                "title": "Fairy Light Lantern",
                "description": "Create a magical ambiance by stuffing the bottle with battery-operated copper wire fairy lights. perfect for nightstands.",
                "difficulty": "Medium",
                "required_tools": ["Fairy Lights (Battery Op)", "Glass Paint (Optional)", "Cork Stopper"]
            },
            {
                "id": 3,
                "type": "Functional Use",
                "title": "Self-Watering Planter",
                "description": "Cut the bottle in half to create a self-watering system for your herbs. The top holds the soil, inverted into the water-filled base.",
                "difficulty": "Hard",
                "required_tools": ["Glass Cutter", "Sandpaper", "Potting Soil", "Cotton String", "Herb Seedling"]
            }
        ]
    },
    ko: {
        "detected_item": "빈 와인 유리병",
        "ideas": [
            {
                "id": 1,
                "type": "쉬운 시작",
                "title": "미니멀 한송이 화병",
                "description": "라벨을 제거하고 병목을 마끈으로 감싸 소박한 느낌을 주는 시크한 화병으로 변신시키세요.",
                "difficulty": "쉬움",
                "required_tools": ["따뜻한 물", "수세미", "마끈", "가위", "투명 풀"]
            },
            {
                "id": 2,
                "type": "감성 데코",
                "title": "무드등 랜턴",
                "description": "배터리로 작동하는 코퍼 와이어 조명을 병 안에 넣어 마법 같은 분위기를 연출하세요. 침대 협탁에 완벽합니다.",
                "difficulty": "보통",
                "required_tools": ["페어리 라이트 (건전지식)", "유리 물감 (선택)", "코르크 마개"]
            },
            {
                "id": 3,
                "type": "실용적 활용",
                "title": "자동 급수 화분",
                "description": "병을 반으로 잘라 허브를 위한 자동 급수 시스템을 만드세요. 윗부분에는 흙을 담고, 물이 담긴 아랫부분에 거꾸로 꽂습니다.",
                "difficulty": "어려움",
                "required_tools": ["유리 절단기", "사포", "분갈이 흙", "면 끈", "허브 모종"]
            }
        ]
    }
};

let currentLang = 'en'; // Default

function initApp() {
    // --- DOM Elements ---
    const dropZone = document.getElementById('drop-zone');
    const fileInput = document.getElementById('file-input');
    const uploadBtn = document.getElementById('upload-btn');
    const imagePreview = document.getElementById('image-preview');
    const previewContainer = document.getElementById('preview-container');
    const removeImageBtn = document.getElementById('remove-image');
    const analyzeBtn = document.getElementById('analyze-btn');
    const loadingOverlay = document.getElementById('loading-overlay');
    const resultsSection = document.getElementById('results-section');
    const ideasContainer = document.getElementById('ideas-container');
    const detectedItemName = document.getElementById('detected-item-name');
    
    // Saved Ideas Elements
    const savedSection = document.getElementById('saved-section');
    const savedContainer = document.getElementById('saved-container');
    const emptySavedState = document.getElementById('empty-saved-state');
    const navSaved = document.getElementById('nav-saved');
    const navHome = document.getElementById('nav-home');
    const btnStartSaving = document.getElementById('btn-start-saving');
    
    // Language Elements
    const btnLang = document.getElementById('btn-lang');

    // Hamburger Menu Logic
    const hamburgerBtn = document.getElementById('hamburger-btn');
    const navMenu = document.getElementById('nav-menu');

    if (hamburgerBtn && navMenu) {
        hamburgerBtn.addEventListener('click', () => {
            hamburgerBtn.classList.toggle('active');
            navMenu.classList.toggle('active');
        });

        // Close menu when a link is clicked
        navMenu.querySelectorAll('a').forEach(link => {
            link.addEventListener('click', () => {
                hamburgerBtn.classList.remove('active');
                navMenu.classList.remove('active');
            });
        });
    }
    
    // --- FAQ Toggle Logic (New) ---
    const faqItems = document.querySelectorAll('.faq-item');
    faqItems.forEach(item => {
        const question = item.querySelector('.faq-question');
        if (question) {
            question.addEventListener('click', () => {
                // Close other items (optional - accordion style)
                faqItems.forEach(otherItem => {
                    if (otherItem !== item) otherItem.classList.remove('active');
                });
                item.classList.toggle('active');
            });
        }
    });

    // --- Language Logic ---
    function updateSEOTags(lang) {
        let canonical = document.querySelector('link[rel="canonical"]');
        if (!canonical) {
            canonical = document.createElement('link');
            canonical.rel = 'canonical';
            document.head.appendChild(canonical);
        }
        
        const baseUrl = window.location.origin + window.location.pathname;
        canonical.href = lang === 'en' ? baseUrl : `${baseUrl}?lang=${lang}`;

        // Alternate tags for SEO
        let altEn = document.querySelector('link[hreflang="en"]');
        if (!altEn) {
            altEn = document.createElement('link');
            altEn.rel = 'alternate';
            altEn.hreflang = 'en';
            document.head.appendChild(altEn);
        }
        altEn.href = baseUrl;

        let altKo = document.querySelector('link[hreflang="ko"]');
        if (!altKo) {
            altKo = document.createElement('link');
            altKo.rel = 'alternate';
            altKo.hreflang = 'ko';
            document.head.appendChild(altKo);
        }
        altKo.href = `${baseUrl}?lang=ko`;

        // x-default
        let altDefault = document.querySelector('link[hreflang="x-default"]');
        if (!altDefault) {
            altDefault = document.createElement('link');
            altDefault.rel = 'alternate';
            altDefault.hreflang = 'x-default';
            document.head.appendChild(altDefault);
        }
        altDefault.href = baseUrl;
    }

    function setLanguage(lang, updateURL = true) {
        if (!TRANSLATIONS[lang]) lang = 'en'; // Safety fallback
        currentLang = lang;
        localStorage.setItem('preferredLang', lang);
        
        // Update URL without reload
        if (updateURL) {
            const newUrl = lang === 'en' 
                ? window.location.pathname 
                : `${window.location.pathname}?lang=${lang}`;
            window.history.pushState({ lang }, '', newUrl);
        }

        // Update SEO Tags
        updateSEOTags(lang);
        
        // Update Document Attributes for CSS Switching
        document.documentElement.setAttribute('data-lang', lang);
        document.documentElement.lang = lang;
        
        // Update Button Text
        if (btnLang) btnLang.textContent = lang === 'en' ? '🇰🇷 KO' : '🇺🇸 EN';

        // Update Text Content
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (TRANSLATIONS[lang] && TRANSLATIONS[lang][key]) {
                if (key === 'footer_text') {
                     el.innerHTML = TRANSLATIONS[lang][key];
                } else {
                    el.textContent = TRANSLATIONS[lang][key];
                }
            }
        });

        // Re-render dynamic content if visible
        if (resultsSection && !resultsSection.classList.contains('hidden')) {
             renderResults(MOCK_DATA[lang]);
        }
        
        if (savedSection && !savedSection.classList.contains('hidden')) {
            renderSavedIdeas();
        }
    }

    // Initialize Language
    const urlParams = new URLSearchParams(window.location.search);
    const langParam = urlParams.get('lang');
    const savedLang = localStorage.getItem('preferredLang');

    if (langParam && TRANSLATIONS[langParam]) {
        setLanguage(langParam, false);
    } else if (savedLang) {
        setLanguage(savedLang, false);
    } else {
        const browserLang = navigator.language.startsWith('ko') ? 'ko' : 'en';
        setLanguage(browserLang, false);
    }

    // Handle back/forward buttons
    window.addEventListener('popstate', (event) => {
        if (event.state && event.state.lang) {
            setLanguage(event.state.lang, false);
        } else {
            // Default to param or fallback
            const currentParams = new URLSearchParams(window.location.search);
            const currentLangParam = currentParams.get('lang') || 'en';
            setLanguage(currentLangParam, false);
        }
    });
    // Toggle Language (Delegated Event for Robustness)
    document.addEventListener('click', (e) => {
        // Handle button or its children (if any)
        if (e.target && (e.target.id === 'btn-lang' || e.target.closest('#btn-lang'))) {
            const newLang = currentLang === 'en' ? 'ko' : 'en';
            setLanguage(newLang);
        }
    });


    // --- Section Visibility Logic ---
    const sections = {
        home: [
            document.getElementById('hero-section'), 
            document.getElementById('upload-section'),
            document.getElementById('static-content'),
            document.getElementById('popular-ideas-section')
        ],
        saved: [savedSection]
    };

    function showSection(sectionName) {
        // If not on index.html, we need to redirect
        if (!document.getElementById('upload-section')) {
             window.location.href = sectionName === 'saved' ? 'index.html#saved' : 'index.html';
             return;
        }

        // Hide all major sections
        Object.values(sections).flat().forEach(el => {
            if(el) el.classList.add('hidden');
        });
        if(resultsSection) resultsSection.classList.add('hidden');
        
        // Show target section
        if (sections[sectionName]) {
            sections[sectionName].forEach(el => {
                if(el) el.classList.remove('hidden');
            });
        }

        if (sectionName === 'saved') {
            renderSavedIdeas();
            window.location.hash = 'saved';
        } else {
             window.location.hash = '';
        }
    }

    // Navigation Events
    if (navSaved) navSaved.addEventListener('click', (e) => {
        if (document.getElementById('upload-section')) {
            e.preventDefault();
            showSection('saved');
        }
    });

    if (navHome) navHome.addEventListener('click', (e) => {
        if (document.getElementById('upload-section')) {
            e.preventDefault();
            showSection('home');
            if (detectedItemName && detectedItemName.textContent !== '...') {
                 // If we have results, we might want to keep showing them? 
                 // Or reset? Let's reset to home state unless we want to keep state.
                 // Actually, if we click Home, we expect the initial state OR the current state.
                 // For simplicity, let's just go to Home state. 
                 // If the user has results, they are in the results section which is separate.
                 // If we want to return to results, we'd need a specific check.
                 // But typically Home means "Start over" or "Top".
                 
                 // If results are visible, let's hide them and show home.
                 resultsSection.classList.add('hidden');
            }
        }
    });

    if (btnStartSaving) btnStartSaving.addEventListener('click', () => {
        showSection('home');
    });

    // Check for hash on load
    if (window.location.hash === '#saved' && document.getElementById('upload-section')) {
        showSection('saved');
    }

    // --- Drag and Drop Events ---
    if (dropZone) {
        ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
            dropZone.addEventListener(eventName, preventDefaults, false);
        });

        function preventDefaults(e) {
            e.preventDefault();
            e.stopPropagation();
        }

        ['dragenter', 'dragover'].forEach(eventName => {
            dropZone.addEventListener(eventName, highlight, false);
        });

        ['dragleave', 'drop'].forEach(eventName => {
            dropZone.addEventListener(eventName, unhighlight, false);
        });

        function highlight() {
            dropZone.classList.add('drag-over');
        }

        function unhighlight() {
            dropZone.classList.remove('drag-over');
        }

        dropZone.addEventListener('drop', handleDrop, false);

        // Click to Upload
        dropZone.addEventListener('click', () => {
            if(previewContainer.classList.contains('hidden')) {
                fileInput.click();
            }
        });
    }

    function handleDrop(e) {
        const dt = e.dataTransfer;
        const files = dt.files;
        handleFiles(files);
    }

    if (uploadBtn) uploadBtn.addEventListener('click', (e) => {
        e.stopPropagation(); 
        fileInput.click();
    });
    
    if (fileInput) fileInput.addEventListener('change', function() {
        handleFiles(this.files);
    });

    function handleFiles(files) {
        if (files.length > 0) {
            const file = files[0];
            if (file.type.startsWith('image/')) {
                previewFile(file);
            } else {
                alert('Please upload an image file.');
            }
        }
    }

    function previewFile(file) {
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onloadend = function() {
            imagePreview.src = reader.result;
            previewContainer.classList.remove('hidden');
            analyzeBtn.classList.remove('hidden');
            analyzeBtn.disabled = false;
        }
    }

    // Remove Image
    removeImageBtn.addEventListener('click', (e) => {
        e.stopPropagation(); 
        imagePreview.src = '';
        previewContainer.classList.add('hidden');
        analyzeBtn.classList.add('hidden');
        analyzeBtn.disabled = true;
        fileInput.value = ''; 
        resultsSection.classList.add('hidden');
        
        // Show static content again
        const staticContent = document.getElementById('static-content');
        const popularIdeas = document.getElementById('popular-ideas-section');
        if(staticContent) staticContent.classList.remove('hidden');
        if(popularIdeas) popularIdeas.classList.remove('hidden');
    });

    // Generate Ideas (Mock AI Call)
    analyzeBtn.addEventListener('click', async () => {
        showLoading(true);
        
        // Simulate network delay
        setTimeout(() => {
            renderResults(MOCK_DATA[currentLang]);
            showLoading(false);
            resultsSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }, 2000);
    });

    function showLoading(show) {
        if (show) {
            loadingOverlay.classList.remove('hidden');
        } else {
            loadingOverlay.classList.add('hidden');
        }
    }

    // --- Saved Ideas Logic ---
    function getSavedIdeas() {
        const saved = localStorage.getItem('savedIdeas');
        return saved ? JSON.parse(saved) : [];
    }

    function toggleSave(idea) {
        const savedIdeas = getSavedIdeas();
        const index = savedIdeas.findIndex(item => item.id === idea.id && item.title === idea.title);
        
        if (index > -1) {
            savedIdeas.splice(index, 1);
        } else {
            savedIdeas.push(idea);
        }
        
        localStorage.setItem('savedIdeas', JSON.stringify(savedIdeas));
        return index === -1; 
    }

    function isSaved(idea) {
        const savedIdeas = getSavedIdeas();
        return savedIdeas.some(item => item.id === idea.id && item.title === idea.title);
    }

    // --- Sharing Logic ---
    async function handleShare(idea) {
        const shareData = {
            title: `Upcycle AI: ${idea.title}`,
            text: `${TRANSLATIONS[currentLang].share_msg} ${idea.title} - ${idea.description}`,
            url: window.location.href
        };

        if (navigator.share) {
            try {
                await navigator.share(shareData);
            } catch (err) {
                console.log('Error sharing:', err);
            }
        } else {
            // Fallback: Copy to clipboard
            try {
                await navigator.clipboard.writeText(`${shareData.text} ${shareData.url}`);
                alert(TRANSLATIONS[currentLang].share_success);
            } catch (err) {
                console.error('Failed to copy: ', err);
            }
        }
    }

    function createCardHTML(idea, saved) {
        let cssClass = 'medium';
        const diffLower = idea.difficulty.toLowerCase();
        if (diffLower.includes('easy') || diffLower.includes('쉬움')) cssClass = 'easy';
        if (diffLower.includes('hard') || diffLower.includes('어려움')) cssClass = 'hard';

        const heartIcon = saved ? '❤️' : '🤍';
        const btnClass = saved ? 'btn-save saved' : 'btn-save';
        
        const saveText = saved ? TRANSLATIONS[currentLang].saved_btn : TRANSLATIONS[currentLang].save_btn;
        const shareText = TRANSLATIONS[currentLang].share_btn;
        const toolsLabel = TRANSLATIONS[currentLang].tools_label;

        return `
            <div class="card-header">
                <span class="card-type">${idea.type}</span>
                <h3 class="card-title">${idea.title}</h3>
                <span class="badge ${cssClass}">${idea.difficulty}</span>
            </div>
            <div class="card-body">
                <p class="card-description">${idea.description}</p>
                <div class="tools-section">
                    <h4>${toolsLabel}</h4>
                    <div class="tools-list">
                        ${idea.required_tools.map(tool => `<span class="tool-tag">${tool}</span>`).join('')}
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button class="btn-share" data-id="${idea.id}" aria-label="Share">
                    🔗 <span>${shareText}</span>
                </button>
                <button class="${btnClass}" data-id="${idea.id}" aria-label="Save to favorites">
                    ${heartIcon} <span>${saveText}</span>
                </button>
            </div>
        `;
    }

    function renderResults(data) {
        if (!detectedItemName || !ideasContainer) return;
        detectedItemName.textContent = data.detected_item;
        ideasContainer.innerHTML = ''; 

        data.ideas.forEach(idea => {
            const card = document.createElement('article');
            card.className = 'idea-card';
            
            const saved = isSaved(idea);
            card.innerHTML = createCardHTML(idea, saved);
            
            const saveBtn = card.querySelector('.btn-save');
            saveBtn.addEventListener('click', () => {
                const isNowSaved = toggleSave(idea);
                const newSaveText = isNowSaved ? TRANSLATIONS[currentLang].saved_btn : TRANSLATIONS[currentLang].save_btn;
                saveBtn.innerHTML = `${isNowSaved ? '❤️' : '🤍'} <span>${newSaveText}</span>`;
                saveBtn.className = isNowSaved ? 'btn-save saved' : 'btn-save';
            });

            const shareBtn = card.querySelector('.btn-share');
            shareBtn.addEventListener('click', () => {
                handleShare(idea);
            });
            
            ideasContainer.appendChild(card);
        });

        resultsSection.classList.remove('hidden');

        // Hide Static Content
        const staticContent = document.getElementById('static-content');
        const popularIdeas = document.getElementById('popular-ideas-section');
        if(staticContent) staticContent.classList.add('hidden');
        if(popularIdeas) popularIdeas.classList.add('hidden');
    }

    function renderSavedIdeas() {
        if (!savedContainer) return;
        const savedIdeas = getSavedIdeas();
        savedContainer.innerHTML = '';

        if (savedIdeas.length === 0) {
            emptySavedState.classList.remove('hidden');
            savedContainer.classList.add('hidden');
            return;
        }

        emptySavedState.classList.add('hidden');
        savedContainer.classList.remove('hidden');

        savedIdeas.forEach(idea => {
            const card = document.createElement('article');
            card.className = 'idea-card';
            card.innerHTML = createCardHTML(idea, true);
            
            const saveBtn = card.querySelector('.btn-save');
            saveBtn.addEventListener('click', () => {
                toggleSave(idea);
                renderSavedIdeas();
            });

            const shareBtn = card.querySelector('.btn-share');
            shareBtn.addEventListener('click', () => {
                handleShare(idea);
            });

            savedContainer.appendChild(card);
        });
    }
}

// Robust Initialization
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initApp);
} else {
    initApp();
}
